name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Time:hhmmss)_$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop/*

pool:
  name: CarMax
  vmImage: ubuntu-latest

parameters:
  - name: MajorMinorVersion
    type: string
    default: '1.0'
  - name: Projects
    type: string
    default: '**/*.sln'
  - name: ProjectName
    type: string
    default: 'CarMaxApi'
  - name: TestProjects
    type: string
    default: '**/*[Tt]ests/[Tt]est*/*.csproj'
  - name: AssemblyVersion
    type: string
    default: "0.0.0.0"
  - name: WorkingDirectory
    type: string
    default: $(Build.SourcesDirectory)
  - name: BuildConfiguration
    type: string
    default: Release
  - name: JdkFilePath
    type: string
    default: 'C:\agents\svr-cr\jdk-11.0.18_windows-x64_bin.zip'
  - name: DotnetSdkVersion
    type: string
    default: 6.x

variables:
  - template: devops/variables/version.yml
    parameters:
      MajorMinorVersion: ${{ parameters.MajorMinorVersion }}

stages:
- stage: Build
  jobs:
  - template: devops/cicd/job.build.dotnet.yml
    parameters:
      JdkFilePath: ${{ parameters.JdkFilePath }}
      DotnetSdkVersion: ${{ parameters.DotnetSdkVersion }}
      Projects: ${{ parameters.Projects }}
      BuildConfiguration: ${{ parameters.BuildConfiguration }}

- stage: Test
  jobs:
  - template: devops/cicd/job.test.dotnet.yml
    parameters:
      TestProjects: ${{ parameters.TestProjects }}
      ProjectName: ${{ parameters.ProjectName }}
      BuildConfiguration: ${{ parameters.BuildConfiguration }}

- stage: Publish
  jobs:
    - template: devops/cicd/job.publish.dotnet.yml
      parameters:
        ProjectName: ${{ parameters.ProjectName }}
        BuildConfiguration: ${{ parameters.BuildConfiguration }}