parameters:
  - name: MajorMinorVersion
    type: string
    default: '1.0'
    
variables:
  MajorMinorVersion: ${{ parameters.MajorMinorVersion }}
  PatchVersion: $[counter(variables['MajorMinorVersion'], 0)]

  versionNumber: $(MajorMinorVersion).$(PatchVersion).$(Build.BuildId)