parameters:
  - name: MajorMinorVersion
    type: string
    default: '1.0'
    
variables:
  MajorMinorVersion: ${{ parameters.MajorMinorVersion }}
  PatchVersion: $[counter(variables['MajorMinorVersion'], 0)]
  buildDate: $(Get-Date -Format yyyyMMdd:hhmmss)
  buildNumber: $(Build.BuildId)

  versionNumber: $(MajorMinorVersion).$(PatchVersion).$(buildNumber)