parameters:
  - name: MajorVersion
    type: number
    default: 1
  - name: MinorVersion
    type: number
    default: 0
    
variables:
  buildDate: $(Get-Date -Format yyyyMMdd:hhmmss)
  buildNumber: $(Build.BuildId)

  version: ${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}.$(Rev:r).$(buildNumber)